#!/bin/bash -x
# update C++ source code that uses the option parser after
# API changes

# get this script with absolute path
thisScript="$(cd $(dirname $0); pwd)/$(basename $0)"

export ignoreList="${ignoreList}$((cat .gitignore 2> /dev/null;svn propget svn:ignore 2> /dev/null;svn propget svn:global-ignores 2> /dev/null) | awk '{sub("/$","");print}')"

for fileOrDir in "$@"; do
    if [ -d "${fileOrDir}" ]; then
	(cd "${fileOrDir}"; ${thisScript} $(ls | grep -v -f <(echo ${ignoreList} | tr ' ' '\n')))
    elif [ -f "${fileOrDir}" ]; then
	if expr "${fileOrDir}" : '.\+\.\(cpp\|C\|h\|hpp\)$'; then
	    echo "processing '${fileOrDir}'"
	    ed -l -v "${fileOrDir}" <<EOF
,s/\<Option[[:space:]]*</options::single</g
,w
EOF
	    ed -l -v "${fileOrDir}" <<EOF
,s/\<OptionContainer[[:space:]]*</options::container</g
,w
EOF
	    ed -l -v "${fileOrDir}" <<EOF
,s/\<OptionMap[[:space:]]*</options::map</g
,w
EOF
	    ed -l -v "${fileOrDir}" <<EOF
,s/\<OptionBase\>/options::base/g
,w
EOF
	    ed -l -v "${fileOrDir}" <<EOF
,s/\<OptionParser\>/options::parser/g
,w
EOF
	else
	    echo "ignoring '${fileOrDir}'"
	fi
    fi
done
