SET(TAGVARIABLENAME ${CMAKE_PROJECT_NAME}_LATEST_TAG)

FIND_package(Git QUIET) # present in 2.8.8
SET(${TAGVARIABLENAME} "0.0")
IF(GIT_EXECUTABLE AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/.git)
	EXECUTE_PROCESS(
		COMMAND
		${GIT_EXECUTABLE} describe --tags --abbrev=0
		WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
		OUTPUT_VARIABLE ${TAGVARIABLENAME}
		ERROR_QUIET
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	IF("" STREQUAL "${${TAGVARIABLENAME}}")
		# No tag yet...
		SET(${TAGVARIABLENAME} "0.0")
	ENDIF()
	MESSAGE(STATUS "Latest tag: ${${TAGVARIABLENAME}}")
ENDIF()
