name: "Compile and Deploy Documentation"

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile with docs and install
      uses: ./docker-action

    - name: Touch .nojekyll
      run: |
        touch html/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./html
        force_orphan: true
